query getEntry($uri: String!) {
  entry(uri: $uri, filter: { status: { in: ["draft", "published"] } }) {
    title
    blueprint
    collection {
      handle
    }
    ... on Entry_Pages_Frontpage {
      id
      description
      hero_body
      hero_image {
        url
        permalink
      }
      hero_title
      hero_link_title
      hero_link
      hero_usp_elements {
        icon {
          value
          label
        }
        text
      }
      replicator_content {
        __typename
        ... on Set_ReplicatorContent_ElementMTekstOgBillede {
          bodytext
          layout
          button_link
          button_text
          layout_direction {
            value
          }
          title
          image_pages {
            ... on Asset_Pages {
              id
              permalink
              width
              height
              alt
            }
          }
          background_color {
            value
          }
        }
        ... on Set_ReplicatorContent_ElementWithTextAndIllustration {
          text
          layout
          layout_direction {
            value
          }
          title
          background {
            value
          }
          button_link
          button_text
          illustration {
            value
          }
        }
      }
    }
  }
}
