query getHeader($handle: String!) {
  header: nav(handle: $handle) {
    title
    tree {
      page {
        title
        url
      }
      children {
        page {
          url
          title
        }
      }
    }
  }
}
