import { gql, request } from 'graphql-request'
import { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

type Props = {
  /** Really hope it is pong */
  ping: string
}

const Home: NextPage<Props> = ({ ping }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Does it return pong: <i>{ping}</i>
        </h1>

        <p>...then we have access to Statamic!</p>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const query = gql`
    {
      ping
    }
  `

  const response = await request(
    'https://www.headless-5cj5jmy-br3bvmw5mdtds.de-2.platformsh.site/graphql',
    query
  )

  return {
    props: {
      ...response,
    },
  }
}

export default Home
