import Head from "next/head";
import styles from "@foundation/ui/styles/Home.module.css";
import { request, gql } from "graphql-request";
import { GetStaticProps, NextPage } from "next";

type Props = {
  /** Really hope it is pong */
  ping: string;
};

const Home: NextPage<Props> = ({ ping }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Does it return pong: <i>{ping}</i>
        </h1>

        <p className={styles.description}>
          ...then we have access to Statamic!
        </p>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const query = gql`
    {
      ping
    }
  `;

  const response = await request(
    "https://www.headless-5cj5jmy-br3bvmw5mdtds.de-2.platformsh.site/graphql",
    query
  );

  return {
    props: {
      ...response,
    },
  };
};

export default Home;
