name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        working-directory: ./playwright
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./playwright
        run: npx playwright test --reporter=html
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: ./playwright/playwright-report/index.html
          retention-days: 30
  deploy:
    name: "Deploy to Github Pages"
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright/playwright-report # This is where index.html will be output
          keep_files: true # Set this to true to make sure we don't wipe out the other content in GitHub Pages
          user_name: "github-actions[bot]" # This will be the username that gets stamped in the repo commit
          user_email: "github-actions[bot]@users.noreply.github.com" # This will be the user email that gets stamped in the repo commit
